learing_users/basicApp/urls.py
from django.urls import path
from basicApp import views

#Template url
app_name='app'


urlpatterns = [
    path('register',views.register,name='register'),
    path('login_user',views.login_user,name='login_user'),

]

learing_users/learing_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from basicApp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basic_app/',include('basicApp.urls')),
    path('logout_user',views.logout_user,name='logout_user'),
    path('special',views.special,name='special')
]

learing_users/basicApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    #create relationship (don't inherit from user!)
    # to add more attribute with first,last name we use OneToOneField
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #it will allow you to Add any Additonal attributes you want
    profile_site=models.URLField(blank=True)# blank=True because user have to fill
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)#user uploaded pics will be stored in profile_pics this foalder

    def __str__(self):
        #Built-in attribute of django.contrib.auth.models.User
        return self.user.username

learing_users/basicApp/forms.py
from  django import forms
from django.contrib.auth.models import User
from basicApp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    #portfolio = forms.URLField(required=False)
    #picture=forms.ImageField(required=False)

     # user model has some attribute we are using thses model attribute for model
    #username,email,password and first_name are user model attribute
    class Meta():
        model=User
        fields=('username','email','password','first_name')


class UserProfileInfo(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('profile_site','profile_pic')

learing_users/basicApp/views.py
from django.shortcuts import render
from basicApp.forms import UserForm,UserProfileInfo


from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls  import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request,'basic_app/index.html')

def register(request):

    registered=False

    if request.method == 'POST':
        User_Form=UserForm(data=request.POST)
        profile_Form=UserProfileInfo(data=request.POST)

        if User_Form.is_valid() and profile_Form.is_valid():
            user=User_Form.save()
            user.set_password(user.password)
            user.save()

            profile= profile_Form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()

            registered =True
        else:
            print(User_Form.errors,profile_Form.errors)

    else:
        User_Form=UserForm()
        profile_Form=UserProfileInfo()

    return render(request,'basic_app/registration.html',
                                {'user_form':User_Form,
                                 'profile_form':profile_Form,
                                 'registered':registered})

def login_user(request):

    if request.method=='POST':
        username=request.POST.get('input_username')
        password=request.POST.get('input_password')

        user=authenticate(username=username,password=password)# django will check the valid UserName and password internally with single line

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not Active')
        else:
            print("some one tried to login and failed!")
            print("Username:{} and password {}".format(username,password))
            return HttpResponse("invalid login details")
    else:
        return render(request,'basic_app/login.html',{})

@login_required # make sure that only logging in user can only logout ..to do that we use decorators @login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse("you have logged nice")

learing_users/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
</head>
<link rel="stylesheet"
href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <ul class="nav navbar-nav"> <!-- navbar-nav -->
      <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
      <li><a class="navbar-brand" href="{% url 'admin:index ' %}">Admin</a></li>
      <li><a class="navbar-brand" href="{% url 'app:register' %}">REGISTER</a></li>

      {% if user.is_authenticated %}
      <li><a class="navbar-link" href="{% url 'logout_user' %}">logout</a></li>

      {% else %}
      <li><a class="navbar-link" href="{% url 'app:login_user' %}">Login</a></li>
      {% endif %}
    </ul>
  </div>
</nav>

<div class="container">
  {% block body_block %}
  {% endblock  %}
</div>
</body>
</html

learing_users/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">

<h2> welcome to Admin</h2>

</div>

{% endblock %}

learing_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1> Please Login</h1>
  <form action="{% url 'app:login_user' %}" method="POST">

        {%csrf_token%}
        <label for="username">UserName:</label>
        <input type="text" name="input_username" >
        <label for="password">password:</label>
        <input type="password" name="input_password" >
        <input type="submit" name="" value="login">
   </form>

</div>

{% endblock %}

learing_users/templates/basic_app/registration.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
{% load staticfiles %}


{% block body_block %}
<div class="jumbotron">
  {% if registered %}
  <h2> thanks for registering!</h2>
  {% else %}
  <h2> Register Here</h2>
  <h2> Fill out the form </h2>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit"name=""  value="Register">
  </form>
{% endif %}
</div>

<h2>this is an example of template inheritence </h2>

{% endblock %}